/**
 * @author pschroen / https://ufo.ai/
 */

export const MaterialProperties = {
    // https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js
    Common: [
        'name',
        'blending',
        // 'side',
        'vertexColors',
        // 'opacity',
        // 'transparent',
        'blendSrc',
        'blendDst',
        'blendEquation',
        'blendSrcAlpha',
        'blendDstAlpha',
        'blendEquationAlpha',
        'blendColor',
        'blendAlpha',
        'depthFunc',
        'depthTest',
        'depthWrite',
        'stencilWriteMask',
        'stencilFunc',
        'stencilRef',
        'stencilFuncMask',
        'stencilFail',
        'stencilZFail',
        'stencilZPass',
        'stencilWrite',
        'clippingPlanes',
        'clipIntersection',
        'clipShadows',
        'shadowSide',
        'colorWrite',
        'precision',
        'polygonOffset',
        'polygonOffsetFactor',
        'polygonOffsetUnits',
        'dithering',
        'alphaTest',
        'alphaHash',
        'alphaToCoverage',
        'premultipliedAlpha',
        'forceSinglePass',
        // 'visible',
        'toneMapped',
        'userData'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshBasicMaterial.js
    Basic: [
        'color',
        'map',
        'lightMap',
        'lightMapIntensity',
        'aoMap',
        'aoMapIntensity',
        'specularMap',
        'alphaMap',
        'envMap',
        'envMapRotation',
        'combine',
        'reflectivity',
        'refractionRatio',
        'wireframe',
        'wireframeLinewidth',
        'wireframeLinecap',
        'wireframeLinejoin',
        'fog'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshLambertMaterial.js
    Lambert: [
        'color',
        'map',
        'lightMap',
        'lightMapIntensity',
        'aoMap',
        'aoMapIntensity',
        'emissive',
        'emissiveMap',
        'emissiveIntensity',
        'bumpMap',
        'bumpScale',
        'normalMap',
        'normalMapType',
        'normalScale',
        'displacementMap',
        'displacementScale',
        'displacementBias',
        'specularMap',
        'alphaMap',
        'envMap',
        'envMapRotation',
        'combine',
        'reflectivity',
        'refractionRatio',
        'wireframe',
        'wireframeLinewidth',
        'wireframeLinecap',
        'wireframeLinejoin',
        'flatShading',
        'fog'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshMatcapMaterial.js
    Matcap: [
        'color',
        'matcap',
        'map',
        'bumpMap',
        'bumpScale',
        'normalMap',
        'normalMapType',
        'normalScale',
        'displacementMap',
        'displacementScale',
        'displacementBias',
        'alphaMap',
        'flatShading',
        'fog'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshPhongMaterial.js
    Phong: [
        'color',
        'specular',
        'shininess',
        'map',
        'lightMap',
        'lightMapIntensity',
        'aoMap',
        'aoMapIntensity',
        'emissive',
        'emissiveMap',
        'emissiveIntensity',
        'bumpMap',
        'bumpScale',
        'normalMap',
        'normalMapType',
        'normalScale',
        'displacementMap',
        'displacementScale',
        'displacementBias',
        'specularMap',
        'alphaMap',
        'envMap',
        'envMapRotation',
        'combine',
        'reflectivity',
        'refractionRatio',
        'wireframe',
        'wireframeLinewidth',
        'wireframeLinecap',
        'wireframeLinejoin',
        'flatShading',
        'fog'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshToonMaterial.js
    Toon: [
        'color',
        'map',
        'gradientMap',
        'lightMap',
        'lightMapIntensity',
        'aoMap',
        'aoMapIntensity',
        'emissive',
        'emissiveMap',
        'emissiveIntensity',
        'bumpMap',
        'bumpScale',
        'normalMap',
        'normalMapType',
        'normalScale',
        'displacementMap',
        'displacementScale',
        'displacementBias',
        'alphaMap',
        'wireframe',
        'wireframeLinewidth',
        'wireframeLinecap',
        'wireframeLinejoin',
        'fog'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshStandardMaterial.js
    Standard: [
        'color',
        'roughness',
        'metalness',
        'map',
        'lightMap',
        'lightMapIntensity',
        'aoMap',
        'aoMapIntensity',
        'emissive',
        'emissiveMap',
        'emissiveIntensity',
        'bumpMap',
        'bumpScale',
        'normalMap',
        'normalMapType',
        'normalScale',
        'displacementMap',
        'displacementScale',
        'displacementBias',
        'roughnessMap',
        'metalnessMap',
        'alphaMap',
        'envMap',
        'envMapRotation',
        'envMapIntensity',
        'wireframe',
        'wireframeLinewidth',
        'wireframeLinecap',
        'wireframeLinejoin',
        'flatShading',
        'fog'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshPhysicalMaterial.js
    Physical: [
        'anisotropy',
        'anisotropyRotation',
        'anisotropyMap',
        'clearcoat',
        'clearcoatMap',
        'clearcoatRoughness',
        'clearcoatRoughnessMap',
        'clearcoatNormalMap',
        'clearcoatNormalScale',
        'dispersion',
        'ior',
        'iridescence',
        'iridescenceMap',
        'iridescenceIOR',
        'iridescenceThicknessRange',
        'iridescenceThicknessMap',
        'sheen',
        'sheenColor',
        'sheenColorMap',
        'sheenRoughness',
        'sheenRoughnessMap',
        'transmission',
        'transmissionMap',
        'thickness',
        'thicknessMap',
        'attenuationDistance',
        'attenuationColor',
        'specularIntensity',
        'specularIntensityMap',
        'specularColor',
        'specularColorMap'
    ],

    // https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshNormalMaterial.js
    Normal: [
        'bumpMap',
        'bumpScale',
        'normalMap',
        'normalMapType',
        'normalScale',
        'displacementMap',
        'displacementScale',
        'displacementBias',
        'wireframe',
        'wireframeLinewidth',
        'flatShading'
    ]
};
